import re

from django_redis import get_redis_connection
from rest_framework.exceptions import ValidationError
